### ISSUE TITLE
Hyperthreading support ?

### ISSUE THREAD

**Issue by xCuri0** [rmullick/bld-patches#1]
It seems these patches don't work with hyperthreading as it requires it disabled

**Comment by rmullick** [comment]
Hyperthreading option has been disabled to make sure it avoids any conflict with mainline load balancer. Since BLD uses different technique for load sharing, so it's fine.

**Comment by xCuri0** [comment]
@rmullick So wouldn't it have problems detecting if it's a virtual thread ?

**Comment by rmullick** [comment]
@xCuri0 No, the option you are talking about isn't about detecting virtual thread, it about utilizing CPU with hyperthreading feature (like most of the commodity processors today) and how scheduler will place task on those CPUs. They introduce this feature like 1 or 2 release back, I think.

BLD uses totally different approach for task placement in case of hyperthreading enabled processor (it depends upon the default group/domain creation). So, you don't need to worry about it, SCHED_SMT is a conflicting feature with BLD, so it's been kept disable.
