### ISSUE TITLE
BLD reduces performance alot

### ISSUE THREAD

**Issue by xCuri0** [rmullick/bld-patches#2]
With BLD I get 4542 for 7zip PTS benchmark and without I get 5060. GLMark2 also gives lower scores (500ish instead of 1300ish).

Dunno if this is an issue but it seems to reduce performance so much that it seems like a bug

**Comment by rmullick** [comment]
@xCuri0 Did you see this issue only in this version? Or also have seen it before? Can you also give me the download link to those benchmark?

**Comment by rmullick** [comment]
@xCuri0  I just ran glmark2 on Linux-4.18. On stable kernel glmark2 score is: 1517 and with BLD : 1488. So, it's not much difference. My graphics related information:

    OpenGL Information
    GL_VENDOR:     Intel Open Source Technology Center
    GL_RENDERER:   Mesa DRI Intel(R) Kabylake GT1.5 
    GL_VERSION:    3.0 Mesa 17.2.8

**Comment by xCuri0** [comment]
@rmullick I haven't tested older versions

```
OpenGL Information
GL_VENDOR:     X.Org
GL_RENDERER:   AMD ARUBA (DRM 2.50.0 / 4.18.6-linuc, LLVM 7.0.0)
GL_VERSION:    3.1 Mesa 18.2.0-devel - padoka PPA
```
My kernel didn't have anything other than compiler flags changed and UKSM (not the cause unless they are conflicting since UKSM without BLD is faster than stock) when I built it

**Comment by xCuri0** [comment]
Can you try the Phoronix Test Suite 7zip-compress benchmark ?

**Comment by rmullick** [comment]
It seems it's with very specific config options, moreover they are not related to scheduler specific issue, I will try to see.

**Comment by figue** [comment]
This issue doesn't happen to me.

Here are my results on my humble laptop, comparing BLD with Archlinux stock and Xanmod kernel. BLD and Arch has the same config (but BLD enabled), Xanmod has it's own config provided by the project:

```
figue@pluto ~ % (head -n8 && tail -n2) </TMP/bench-arch.txt 
Linux pluto 4.18.7-arch1-1-ARCH #1 SMP PREEMPT Sun Sep 9 11:27:58 UTC 2018 x86_64 GNU/Linux
=======================================================
    glmark2 2017.07
=======================================================
    OpenGL Information
    GL_VENDOR:     Intel Open Source Technology Center
    GL_RENDERER:   Mesa DRI Intel(R) Ironlake Mobile 
    GL_VERSION:    2.1 Mesa 18.2.0
=======================================================
                                  glmark2 Score: 163 
=======================================================
```

```
figue@pluto ~ % (head -n8 && tail -n3) </TMP/bench-xanmod.txt 
Linux pluto 4.18.6-1-xanmod4 #1 SMP PREEMPT Sun Sep 9 12:00:59 CEST 2018 x86_64 GNU/Linux

=======================================================
    glmark2 2017.07
=======================================================
    OpenGL Information
    GL_VENDOR:     Intel Open Source Technology Center
    GL_RENDERER:   Mesa DRI Intel(R) Ironlake Mobile 
    GL_VERSION:    2.1 Mesa 18.2.0
=======================================================
                                  glmark2 Score: 164 
=======================================================
```

```
figue@pluto ~ % (head -n8 && tail -n3) </TMP/bench-bld.txt   
Linux pluto 4.18.5-1-bld #1 SMP PREEMPT Sun Aug 26 11:10:05 CEST 2018 x86_64 GNU/Linux
=======================================================
    glmark2 2017.07
=======================================================
    OpenGL Information
    GL_VENDOR:     Intel Open Source Technology Center
    GL_RENDERER:   Mesa DRI Intel(R) Ironlake Mobile 
    GL_VERSION:    2.1 Mesa 18.2.0
=======================================================
                                  glmark2 Score: 163 
=======================================================
```

Hope it helps. I can do more tests if there are interest.

**Comment by rmullick** [comment]
@figue - Thanks for sharing the benchmark info. As @xCuri0 mentioned - it's more of an issue with UKSM. So far, after doing some google search it appears that, it's not in the mainline yet, there's a closest variant of this feature is KSM which is in the mainline.

Regarding testing, it would be nice if you can (if have access) do scheduler related testing on mid-range boxes like. 8 core HT or similar or more. I think it'd be interesting to see the performance of BLD on those systems.

**Comment by figue** [comment]
My top box right now is an old i5 (ivy-bridge) with 4 cores.

**Comment by rmullick** [comment]
@figue I have already went through this kind of boxes and the difference won't be much noticeable either.
